service: graphql-rest

plugins:
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-dynamodb

package:
  exclude:
    - images/**
    - esbuild/**
    - bundle/**
    - ada/**
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - sample.graphql
    - .env.*
    - .eslintrc.*
    - .prettierrc
    - nest-cli.json
    - tsconfig.json
    - tsconfig.build.json
    - ada/**
    - build/**
    - README.md
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  profile: default # Config your AWS Profile
  environment: # Service wide environment variables
    NODE_ENV: production
    # AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    # NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

functions:
  app:
    handler: dist/serverless.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any