service: api-rest

package:
  excludeDevDependencies: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  profile: default # Config your AWS Profile
  environment: # Service wide environment variables
    NODE_ENV: production
    # AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    # NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

functions:
  app:
    handler: src/serverless.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any
